set-option -g focus-events on
set-option -g default-terminal "tmux-256color"
set -g extended-keys on
set -g extended-keys-format csi-u

# use with alacritty
set-option -a terminal-features "alacritty:RGB"

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# change the default prefix
set -g prefix2 C-a

# reload config on r
unbind r
bind r source-file ~/.tmux.conf

# history
set -g history-limit 10000

# navigation

# enable mouse
set -g mouse on

# change default keybindings
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# pane indexing
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# status bar
set -g status-position top
set -g status-justify left
set -g status-left-length 40
set -g status-right-length 80

# left: empty
set -g status-left ""

# right: battery + time + session
set -g status-right "bat #{battery_percentage} | %H:%M | #S "

set -g status-bg cyan

# windows
set -g window-status-format "  #I:#W  "

set -g window-status-current-format "  [#I:#W]  "

set -g window-status-separator ""

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'

run '~/.tmux/plugins/tpm/tpm'
